### ISSUE TITLE
Config to disable items?

### ISSUE THREAD

**Issue by EllieShrug** [Justin-YCheese/RoR2Ultitem#2]
I think a few items are very fun, I loved playing with the lunar that shrine of orders you every time you pick up an item... but some items just don't meld with my modpack, like frisbee really messes with the flying characters I've added. Any chance Sonorous Pail could get a standalone version or you could add a config to pick items we want, that'd likely be easier than making a standalone version. If this already exists I can't seem to access it in r2modman.

**Comment by Justin-YCheese** [comment]
I'm glad to see I'm not the only one who will actively pickup Sonorous Pail! (My friends wouldn't)

I'm sorry to hear that frisbee doesn't meld well with your character. I was hoping that none of the items will pose too much of a problem but that is more of a dream than a possibility when modding...

There is a mod already called ItemBlacklist By Thrayonlosa (https://thunderstore.io/package/Thrayonlosa/) which can remove items from the game, but when I tried to use it the UI isn't the best.

I'll look into making a config file that can toggle the items on and off.

**Comment by EllieShrug** [comment]
Thanks, because I would definitely like some of these in my pack, my friends have their favorites as well. I might check out the blacklist but a config would be ideal.

**Comment by EllieShrug** [comment]
oh yeah, wow, that blacklist mod isn't great. Not only does it not save my changes on a relaunch (which also means my less experienced friends will have the items that can bug out some characters) but it also randomly disables some base game items on launch (old guillotine and transcendence, for some unknowable reason.) , so that is cool.

**Comment by EllieShrug** [comment]
Thanks so much for the update!
